Repository GEOS-ESM/GMI, pull requests merged in 2025-09, with the labels that each got.

#37 Details that arose in CTM tests
  CHANGELOG.md
  GMI_GridComp/GmiChem_GridCompClassMod.F90
  GMI_GridComp/GmiEmission/harvard/emiss_harvard.F90
  GMIchem_GridCompMod.F90
Labels: 0 diff

#38 minimal mechanism
  .github/workflows/spack-ci.yml
  CHANGELOG.md
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/GMI_GridComp.rc
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/GMI_Mech_Registry.rc
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/GMI_Registry.rc
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_chem_mech.txt
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_depos.h
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_fastj.h
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_group.h
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_ibcb.h
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_kcalc.F90
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_lchem.h
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_mw.h
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_par.h
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_ratecalc.F90
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_smv2.h
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_smv2par.h
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_surf_bc.h
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/setkin_synspc.h
Labels: Non 0-diff, enhancement

#41 Feature/ssteenro/no bc real time using gocart xx
  CHANGELOG.md
  GMI_GridComp/GmiChemistry/Standard/GMI_GridComp.rc
  GMI_GridComp/GmiChemistry/StratTrop_HFC_S/GMI_GridComp.rc
  GMI_GridComp/GmiChemistry/StratTrop_HFC_S_Pyro/GMI_GridComp.rc
  GMI_GridComp/GmiChemistry/StratTrop_JPL19/GMI_GridComp.rc
  GMI_GridComp/GmiChemistry/StratTrop_Minimal/GMI_GridComp.rc
  GMI_GridComp/GmiChemistry/StratTrop_Orig/GMI_GridComp.rc
  GMI_GridComp/GmiDepos_GridCompClassMod.F90
  GMI_GridComp/GmiEmiss_GridCompClassMod.F90
  GMI_GridComp/GmiForcingBC_GridCompClassMod.F90
  GMI_GridComp/GmiPhotolysis_GridCompClassMod.F90
Labels: 0 diff trivial
